Check against the name of the file
DavidBabel/Switch-Backup-Rename pull request #3
Opened 2019-02-16 14:01 UTC by MatthieuGaidoz

Juste quelques changement pour checker sur le nom des fichier. 
Comme je suis sur windows j'ai du faire quelques changement sur le code (et rajouter un dossier pour pouvoir tester). 

Le code est pas très beau mais c'est plus pour donner une idée.

2019-02-16 15:07 UTC, DavidBabel commented
Merci mec, je check ça au plus vite

2019-02-17 20:49 UTC, DavidBabel requested changes

2019-02-17 20:49 UTC, DavidBabel commented on _switch-backup-rename.js
> +          const cleanedFileName = cleanFileName(accents.remove(finalName));
Ce cleanFileName en dehors d'un try catch est risqué. Si il manque des infos dans le JSON pour un certain titre, le programme va crash

2019-02-17 20:49 UTC, DavidBabel commented on debug/games.json.bkp
> +{"updated":1550292970292,"datas":[{"id":"1","name":"The Legend of Zelda: Breath of the Wild","publisher":"Nintendo","region":"WLD","languages":"en,fr,de,it,es,ru,ja","group":"BigBlueBox","imagesize":
ne devrait pas être présent, si ?

2019-02-17 20:49 UTC, DavidBabel commented on utils/filter-helpers.js
> +  // This one is maybe useless now ?
Bah je pense pas, je l'avais justement ajouté car dans certains cas c'est le seul moyen de trouvé un match

2019-02-18 01:38 UTC, MatthieuGaidoz commented on utils/filter-helpers.js
> +  // This one is maybe useless now ?
Vu qu'il y a mon code qui check maintenant le nom checker la release c'est a peu de chose pres la meme chose

2019-02-18 01:38 UTC, MatthieuGaidoz commented on _switch-backup-rename.js
> +          const cleanedFileName = cleanFileName(accents.remove(finalName));
Je ne pense pas, finalName est un string normal.
Il n'est en aucun cas dependant du json (au pire il est vide ou null).
peut être qu'il y a juste ca a tester en plus

2019-02-18 01:39 UTC, MatthieuGaidoz commented on debug/games.json.bkp
> +{"updated":1550292970292,"datas":[{"id":"1","name":"The Legend of Zelda: Breath of the Wild","publisher":"Nintendo","region":"WLD","languages":"en,fr,de,it,es,ru,ja","group":"BigBlueBox","imagesize":
Nope mais il manque le games.json de test par contre

2019-02-18 01:40 UTC, MatthieuGaidoz commented
Bref comme dis précédemment c'est plus pour te donner une idée.
Si tu veux juste reprendre une partie de mon code fait le :).

Pas besoin de merger cette PR c’était plus pour te donner un coup de main ;)

2019-02-20 16:04 UTC, DavidBabel commented
Ca marche je regarderais ce que je peux faire

2019-06-13 01:40 UTC, closed without merging